---
- name: Install Spring-pet
  hosts: all

  tasks:
  - name: Install prerequisites
    package:
      name:
      - epel-release
      - git
      state: present

  - name: Install Java
    package:
      name: 
      - java-1.8.0-openjdk-devel
      state: present

  - name: Pull spring-petclinic
    git:
      repo: "{{ spring_repo }}"
      version: "{{ spring_branch }}"
      dest: /var/www/spring-petclinic/

  - name: Install Maven
    shell: " ./mvnw package "
  
  - name: Starting Spring-Petclinic Java
    shell: "nohup java -jar /var/www/spring-petclinic/target/spring-petclinic-2.3.1.BUILD-SNAPSHOT.jar &"

