---
- name: Install Spring-pet
  hosts: all
  user: centos
  become: yes
  become_method: sudo

  tasks:
  - name: Install prerequisites
    package:
      name:
      - epel-release
      - git
      state: present

  - name: Install Java
    package:
      name: 
      - java-1.8.0-openjdk-devel
      state: present

  - name: Pull spring-petclinic
    git:
      repo: "{{ spring_repo }}"
      version: "{{ spring_branch }}"
      dest: /var/www/spring-petclinic/

  - name: Install Maven
    shell: " ./mvnw package "
  
  - name: Start App
    shell: "mv target/*.jar /var/www/spring-petclinc/target/app.jar &"
    shell: "nohup java -jar app.jar /var/www/spring-petclinic/target &"

