---
- hosts: all

  tasks:
  - name: Starting Spring-Petclinic Java
    shell: "mv target/*.jar /var/www/spring-petclinc/target/app.jar &"
    shell: "nohup java -jar app.jar /var/www/spring-petclinic/target &"